spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    fetch-registry: false #false cause this server itself
    register-with-eureka: false #false cause this is the server itself
